# ==============================================================
# ArgoCD Application - GitOps workflow for Kubernetes (Helm)
# ==============================================================
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chikwex-eshopz
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/LycanTech/Chikwex-Infra.git
    targetRevision: main
    path: Assignment7/CompleteCI-CDPipeline/helm/chikwex-eshopz
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: chikwex-eshopz
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chikwex-monitoring
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/LycanTech/Chikwex-Infra.git
    targetRevision: main
    path: Assignment7/CompleteCI-CDPipeline/k8s/monitoring
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
